# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VXSSON4_e0nsLNDuHhZXIe13xbCsK7A8
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("nasa/kepler-exoplanet-search-results")

print("Path to dataset files:", path)

!pip install imblearn

!pip install xgboost

import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error
)
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from imblearn.over_sampling import SMOTE

import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    f1_score,
    precision_score,
    recall_score,
)

from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier

# ---------------------------------------------------------------------------
# Load & clean data
# ---------------------------------------------------------------------------
data = pd.read_csv(
    "/root/.cache/kagglehub/datasets/nasa/kepler-exoplanet-search-results/versions/2/cumulative.csv"
)

drop_cols = [
    "rowid", "kepid", "kepoi_name", "kepler_name",
    "koi_teq_err1", "koi_teq_err2", "koi_pdisposition", "koi_tce_delivname",
]
data.drop(columns=drop_cols, inplace=True)

y = data["koi_disposition"].map({
    "CONFIRMED": 1,
    "CANDIDATE": 2,
    "FALSE POSITIVE": 0,
})
X = data.drop(columns=["koi_disposition"])

# ---------------------------------------------------------------------------
# Split FIRST, then fit preprocessing/resampling only on the training data
# ---------------------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y,
)

num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
])

preprocessor = ColumnTransformer([
    ("num", num_pipeline, X.columns),
])

# Fit imputer on train only, then transform both
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

# SMOTE on training data only — test set stays 100% real
smote = SMOTE(random_state=42)
X_train, y_train = smote.fit_resample(X_train, y_train)

print(f"Train size after SMOTE: {X_train.shape[0]}, Test size (untouched): {X_test.shape[0]}")





# ---------------------------------------------------------------------------
# GradientBoostingClassifier
# ---------------------------------------------------------------------------
print("\n=== GradientBoostingClassifier ===")

xg = GradientBoostingClassifier(random_state=42)
xg.fit(X_train, y_train)

y_pred_gb = xg.predict(X_test)

print(f"Accuracy score: {accuracy_score(y_test, y_pred_gb)}")
print(f"F1 score: {f1_score(y_test, y_pred_gb, average='macro')}")
print(f"Precision score: {precision_score(y_test, y_pred_gb, average='macro')}")
print(f"Recall score: {recall_score(y_test, y_pred_gb, average='macro')}")
print(f"Confusion matrix:\n{confusion_matrix(y_test, y_pred_gb)}")
print(f"Classification report:\n{classification_report(y_test, y_pred_gb)}")

import pickle

with open("kepler_gradient_boosting.pkl", "wb") as f:
    pickle.dump(xg, f)

with open("preprocessor.pkl", "wb") as f:
    pickle.dump(preprocessor, f)

from google.colab import files


# files.download('kepler_gradient_boosting.pkl')
files.download('preprocessor.pkl')
